/**
 * Seed recipe library. Ingredient names are lowercase and deliberately
 * consistent across recipes ("crushed tomatoes", not "tinned tomatoes" in one
 * and "tomato passata" in another) so the shopping list can merge them.
 *
 * Ingredient tuple: [name, quantity, unit, aisle]
 */

export const AISLES = [
  "Produce",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Refrigerated",
  "Bakery",
  "Frozen",
  "Pantry",
  "Spices & Herbs",
  "Beverages",
];

/**
 * Each recipe: { name, emoji, slots (comma-separated breakfast|lunch|dinner),
 * servings, minutes, tags, description, ingredients }
 */
export const RECIPES = [
  {
    name: "Greek Yogurt Berry Bowl",
    emoji: "🫐",
    slots: "breakfast",
    servings: 2,
    minutes: 5,
    tags: "vegetarian,no-cook,high-protein",
    description: "Thick yogurt, warm honey, and enough granola for crunch in every spoonful.",
    ingredients: [
      ["greek yogurt", 400, "g", "Dairy & Eggs"],
      ["blueberries", 150, "g", "Produce"],
      ["honey", 2, "tbsp", "Pantry"],
      ["granola", 80, "g", "Pantry"],
      ["almonds", 30, "g", "Pantry"],
    ],
  },
  {
    name: "Spinach Mushroom Omelette",
    emoji: "🍳",
    slots: "breakfast",
    servings: 2,
    minutes: 15,
    tags: "vegetarian,high-protein,low-carb",
    description: "Mushrooms browned properly first, so the eggs stay custardy.",
    ingredients: [
      ["eggs", 4, "", "Dairy & Eggs"],
      ["spinach", 100, "g", "Produce"],
      ["cremini mushrooms", 150, "g", "Produce"],
      ["butter", 15, "g", "Dairy & Eggs"],
      ["parmesan", 30, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Banana Oat Pancakes",
    emoji: "🥞",
    slots: "breakfast",
    servings: 4,
    minutes: 25,
    tags: "vegetarian,kid-friendly,batch",
    description: "Blender batter, no flour. They freeze well, so make the full stack.",
    ingredients: [
      ["rolled oats", 200, "g", "Pantry"],
      ["banana", 2, "", "Produce"],
      ["eggs", 2, "", "Dairy & Eggs"],
      ["milk", 240, "ml", "Dairy & Eggs"],
      ["baking powder", 1, "tsp", "Pantry"],
      ["maple syrup", 60, "ml", "Pantry"],
    ],
  },
  {
    name: "Avocado Toast with Chili Crisp",
    emoji: "🥑",
    slots: "breakfast,lunch",
    servings: 2,
    minutes: 10,
    tags: "vegan,quick",
    description: "Sourdough toasted hard, avocado smashed rough, chili crisp poured without restraint.",
    ingredients: [
      ["sourdough bread", 4, "slice", "Bakery"],
      ["avocado", 2, "", "Produce"],
      ["lime", 1, "", "Produce"],
      ["chili crisp", 2, "tbsp", "Pantry"],
      ["flaky salt", 1, "tsp", "Spices & Herbs"],
    ],
  },
  {
    name: "Peanut Butter Overnight Oats",
    emoji: "🥜",
    slots: "breakfast",
    servings: 2,
    minutes: 5,
    tags: "vegetarian,make-ahead,no-cook",
    description: "Five minutes tonight buys you a breakfast you don't have to think about.",
    ingredients: [
      ["rolled oats", 120, "g", "Pantry"],
      ["milk", 300, "ml", "Dairy & Eggs"],
      ["chia seeds", 2, "tbsp", "Pantry"],
      ["peanut butter", 3, "tbsp", "Pantry"],
      ["banana", 1, "", "Produce"],
    ],
  },
  {
    name: "Shakshuka",
    emoji: "🍅",
    slots: "breakfast,dinner",
    servings: 3,
    minutes: 30,
    tags: "vegetarian,one-pan",
    description: "Eggs poached in spiced tomato until the whites set and the yolks don't.",
    ingredients: [
      ["eggs", 5, "", "Dairy & Eggs"],
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 1, "", "Produce"],
      ["red bell pepper", 1, "", "Produce"],
      ["garlic", 3, "clove", "Produce"],
      ["cumin", 1, "tsp", "Spices & Herbs"],
      ["feta", 100, "g", "Dairy & Eggs"],
      ["cilantro", 1, "bunch", "Produce"],
    ],
  },
  {
    name: "Chickpea Salad Wraps",
    emoji: "🌯",
    slots: "lunch",
    servings: 2,
    minutes: 15,
    tags: "vegetarian,no-cook,packable",
    description: "Mashed chickpeas standing in for tuna, with enough celery to stay crunchy.",
    ingredients: [
      ["chickpeas", 400, "g", "Pantry"],
      ["mayonnaise", 3, "tbsp", "Pantry"],
      ["celery", 2, "stalk", "Produce"],
      ["red onion", 0.5, "", "Produce"],
      ["lemon", 1, "", "Produce"],
      ["flour tortilla", 2, "", "Bakery"],
      ["lettuce", 60, "g", "Produce"],
    ],
  },
  {
    name: "Sesame Soba Noodle Salad",
    emoji: "🍜",
    slots: "lunch",
    servings: 3,
    minutes: 20,
    tags: "vegan,packable,make-ahead",
    description: "Cold noodles, loud dressing. Better on day two than day one.",
    ingredients: [
      ["soba noodles", 250, "g", "Pantry"],
      ["cucumber", 1, "", "Produce"],
      ["carrot", 2, "", "Produce"],
      ["scallions", 4, "", "Produce"],
      ["soy sauce", 45, "ml", "Pantry"],
      ["sesame oil", 2, "tbsp", "Pantry"],
      ["sesame seeds", 2, "tbsp", "Pantry"],
      ["edamame", 200, "g", "Frozen"],
    ],
  },
  {
    name: "Tomato Soup & Grilled Cheese",
    emoji: "🥣",
    slots: "lunch,dinner",
    servings: 4,
    minutes: 35,
    tags: "vegetarian,comfort,kid-friendly",
    description: "The soup gets cream and basil; the sandwich gets butter on the outside.",
    ingredients: [
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 1, "", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["heavy cream", 120, "ml", "Dairy & Eggs"],
      ["basil", 1, "bunch", "Produce"],
      ["sourdough bread", 8, "slice", "Bakery"],
      ["cheddar", 200, "g", "Dairy & Eggs"],
      ["butter", 40, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Turkey Pesto Panini",
    emoji: "🥪",
    slots: "lunch",
    servings: 2,
    minutes: 15,
    tags: "quick,high-protein",
    description: "Press it under something heavy until the cheese leaks and crisps.",
    ingredients: [
      ["ciabatta roll", 2, "", "Bakery"],
      ["sliced turkey", 200, "g", "Meat & Seafood"],
      ["pesto", 60, "g", "Pantry"],
      ["mozzarella", 120, "g", "Dairy & Eggs"],
      ["roasted red pepper", 100, "g", "Pantry"],
      ["arugula", 40, "g", "Produce"],
    ],
  },
  {
    name: "Quinoa Halloumi Bowl",
    emoji: "🥗",
    slots: "lunch,dinner",
    servings: 2,
    minutes: 25,
    tags: "vegetarian,high-protein",
    description: "Halloumi seared until squeaky, over lemony quinoa and cold tomatoes.",
    ingredients: [
      ["quinoa", 150, "g", "Pantry"],
      ["halloumi", 200, "g", "Dairy & Eggs"],
      ["cherry tomatoes", 200, "g", "Produce"],
      ["cucumber", 1, "", "Produce"],
      ["olive oil", 3, "tbsp", "Pantry"],
      ["lemon", 1, "", "Produce"],
      ["mint", 1, "bunch", "Produce"],
    ],
  },
  {
    name: "Black Bean Quesadillas",
    emoji: "🫓",
    slots: "lunch,dinner",
    servings: 3,
    minutes: 20,
    tags: "vegetarian,kid-friendly,quick",
    description: "Crisp tortilla, molten jack, charred corn. Ready before anyone asks twice.",
    ingredients: [
      ["black beans", 400, "g", "Pantry"],
      ["flour tortilla", 6, "", "Bakery"],
      ["monterey jack", 200, "g", "Dairy & Eggs"],
      ["corn", 150, "g", "Frozen"],
      ["scallions", 3, "", "Produce"],
      ["cumin", 1, "tsp", "Spices & Herbs"],
      ["sour cream", 100, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Caprese Orzo Salad",
    emoji: "🍅",
    slots: "lunch",
    servings: 3,
    minutes: 20,
    tags: "vegetarian,packable",
    description: "Orzo dressed while still warm so it drinks up the balsamic.",
    ingredients: [
      ["orzo", 250, "g", "Pantry"],
      ["cherry tomatoes", 300, "g", "Produce"],
      ["mozzarella", 150, "g", "Dairy & Eggs"],
      ["basil", 1, "bunch", "Produce"],
      ["olive oil", 3, "tbsp", "Pantry"],
      ["balsamic vinegar", 2, "tbsp", "Pantry"],
      ["pine nuts", 30, "g", "Pantry"],
    ],
  },
  {
    name: "Sheet-Pan Lemon Chicken",
    emoji: "🍗",
    slots: "dinner",
    servings: 4,
    minutes: 45,
    tags: "one-pan,high-protein",
    description: "Everything on one tray; the potatoes cook in the chicken fat.",
    ingredients: [
      ["chicken thighs", 800, "g", "Meat & Seafood"],
      ["baby potatoes", 700, "g", "Produce"],
      ["lemon", 2, "", "Produce"],
      ["garlic", 6, "clove", "Produce"],
      ["olive oil", 60, "ml", "Pantry"],
      ["rosemary", 2, "tbsp", "Spices & Herbs"],
      ["green beans", 300, "g", "Produce"],
    ],
  },
  {
    name: "Weeknight Bolognese",
    emoji: "🍝",
    slots: "dinner",
    servings: 4,
    minutes: 50,
    tags: "comfort,batch,kid-friendly",
    description: "Not a four-hour ragù, but the soffritto still gets its full ten minutes.",
    ingredients: [
      ["ground beef", 500, "g", "Meat & Seafood"],
      ["spaghetti", 400, "g", "Pantry"],
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 1, "", "Produce"],
      ["carrot", 2, "", "Produce"],
      ["celery", 2, "stalk", "Produce"],
      ["garlic", 3, "clove", "Produce"],
      ["red wine", 120, "ml", "Beverages"],
      ["parmesan", 60, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Thai Green Curry with Tofu",
    emoji: "🍛",
    slots: "dinner",
    servings: 4,
    minutes: 35,
    tags: "vegan,one-pot",
    description: "Fry the paste in coconut cream until it splits — that's where the flavour is.",
    ingredients: [
      ["firm tofu", 400, "g", "Refrigerated"],
      ["coconut milk", 400, "ml", "Pantry"],
      ["green curry paste", 3, "tbsp", "Pantry"],
      ["jasmine rice", 300, "g", "Pantry"],
      ["thai basil", 1, "bunch", "Produce"],
      ["bamboo shoots", 200, "g", "Pantry"],
      ["lime", 2, "", "Produce"],
      ["fish sauce", 1, "tbsp", "Pantry"],
    ],
  },
  {
    name: "Miso Glazed Salmon",
    emoji: "🐟",
    slots: "dinner",
    servings: 2,
    minutes: 25,
    tags: "high-protein,quick",
    description: "Broiled close to the element so the glaze lacquers instead of steaming.",
    ingredients: [
      ["salmon fillet", 400, "g", "Meat & Seafood"],
      ["white miso", 2, "tbsp", "Refrigerated"],
      ["mirin", 2, "tbsp", "Pantry"],
      ["honey", 1, "tbsp", "Pantry"],
      ["jasmine rice", 150, "g", "Pantry"],
      ["bok choy", 300, "g", "Produce"],
      ["ginger", 1, "tbsp", "Produce"],
    ],
  },
  {
    name: "Smoky Black Bean Chili",
    emoji: "🌶️",
    slots: "dinner",
    servings: 5,
    minutes: 55,
    tags: "vegan,batch,freezer",
    description: "Chipotle and smoked paprika doing the work of an all-day simmer.",
    ingredients: [
      ["black beans", 800, "g", "Pantry"],
      ["kidney beans", 400, "g", "Pantry"],
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 2, "", "Produce"],
      ["red bell pepper", 2, "", "Produce"],
      ["smoked paprika", 1, "tbsp", "Spices & Herbs"],
      ["chipotle in adobo", 2, "tbsp", "Pantry"],
      ["cumin", 1, "tbsp", "Spices & Herbs"],
      ["sour cream", 150, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Mushroom Risotto",
    emoji: "🍚",
    slots: "dinner",
    servings: 4,
    minutes: 45,
    tags: "vegetarian,comfort",
    description: "Twenty minutes of stirring, then butter and parmesan off the heat.",
    ingredients: [
      ["arborio rice", 320, "g", "Pantry"],
      ["cremini mushrooms", 400, "g", "Produce"],
      ["shallot", 2, "", "Produce"],
      ["white wine", 150, "ml", "Beverages"],
      ["vegetable broth", 1.2, "l", "Pantry"],
      ["parmesan", 80, "g", "Dairy & Eggs"],
      ["butter", 50, "g", "Dairy & Eggs"],
      ["thyme", 1, "tbsp", "Spices & Herbs"],
    ],
  },
  {
    name: "Korean Beef Bulgogi Bowls",
    emoji: "🥩",
    slots: "dinner",
    servings: 4,
    minutes: 35,
    tags: "high-protein,grill",
    description: "Grated pear in the marinade tenderises the steak and helps it caramelise.",
    ingredients: [
      ["flank steak", 600, "g", "Meat & Seafood"],
      ["soy sauce", 80, "ml", "Pantry"],
      ["brown sugar", 3, "tbsp", "Pantry"],
      ["pear", 1, "", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["sesame oil", 2, "tbsp", "Pantry"],
      ["jasmine rice", 300, "g", "Pantry"],
      ["kimchi", 200, "g", "Refrigerated"],
      ["scallions", 4, "", "Produce"],
    ],
  },
  {
    name: "Roasted Cauliflower Tacos",
    emoji: "🌮",
    slots: "dinner",
    servings: 4,
    minutes: 40,
    tags: "vegetarian,sheet-pan",
    description: "Cauliflower roasted until the edges go black, with a quick chipotle crema.",
    ingredients: [
      ["cauliflower", 800, "g", "Produce"],
      ["corn tortilla", 12, "", "Bakery"],
      ["chipotle in adobo", 1, "tbsp", "Pantry"],
      ["red cabbage", 200, "g", "Produce"],
      ["lime", 2, "", "Produce"],
      ["greek yogurt", 150, "g", "Dairy & Eggs"],
      ["cilantro", 1, "bunch", "Produce"],
      ["cumin", 2, "tsp", "Spices & Herbs"],
    ],
  },
  {
    name: "Lemon Garlic Shrimp Pasta",
    emoji: "🍤",
    slots: "dinner",
    servings: 3,
    minutes: 30,
    tags: "quick,high-protein",
    description: "Shrimp in and out in three minutes; the sauce is butter, lemon, and pasta water.",
    ingredients: [
      ["shrimp", 500, "g", "Meat & Seafood"],
      ["linguine", 300, "g", "Pantry"],
      ["butter", 60, "g", "Dairy & Eggs"],
      ["garlic", 5, "clove", "Produce"],
      ["lemon", 2, "", "Produce"],
      ["parsley", 1, "bunch", "Produce"],
      ["chili flakes", 1, "tsp", "Spices & Herbs"],
      ["white wine", 120, "ml", "Beverages"],
    ],
  },
  {
    name: "Chicken Tikka Masala",
    emoji: "🍛",
    slots: "dinner",
    servings: 4,
    minutes: 50,
    tags: "comfort,high-protein",
    description: "Yogurt-marinated chicken charred first, then folded into a creamy tomato gravy.",
    ingredients: [
      ["chicken breast", 700, "g", "Meat & Seafood"],
      ["greek yogurt", 200, "g", "Dairy & Eggs"],
      ["garam masala", 2, "tbsp", "Spices & Herbs"],
      ["crushed tomatoes", 400, "g", "Pantry"],
      ["heavy cream", 150, "ml", "Dairy & Eggs"],
      ["onion", 1, "", "Produce"],
      ["ginger", 2, "tbsp", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["basmati rice", 300, "g", "Pantry"],
      ["naan", 4, "", "Bakery"],
    ],
  },
  {
    name: "Egg Fried Rice",
    emoji: "🍳",
    slots: "lunch,dinner",
    servings: 3,
    minutes: 20,
    tags: "quick,leftovers,kid-friendly",
    description: "Day-old rice, a very hot pan, and everything prepped before you start.",
    ingredients: [
      ["jasmine rice", 300, "g", "Pantry"],
      ["eggs", 3, "", "Dairy & Eggs"],
      ["peas", 150, "g", "Frozen"],
      ["carrot", 1, "", "Produce"],
      ["scallions", 3, "", "Produce"],
      ["soy sauce", 3, "tbsp", "Pantry"],
      ["sesame oil", 1, "tbsp", "Pantry"],
      ["garlic", 2, "clove", "Produce"],
    ],
  },

  // ── Breakfast ──────────────────────────────────────────────────────────────

  {
    name: "Chia Pudding with Mango",
    emoji: "🥭",
    slots: "breakfast",
    servings: 2,
    minutes: 5,
    tags: "vegan,make-ahead,no-cook",
    description: "Stir it together before bed; wake up to something that actually looks like effort.",
    ingredients: [
      ["chia seeds", 60, "g", "Pantry"],
      ["coconut milk", 400, "ml", "Pantry"],
      ["mango", 1, "", "Produce"],
      ["maple syrup", 2, "tbsp", "Pantry"],
      ["lime", 1, "", "Produce"],
    ],
  },
  {
    name: "French Toast with Berries",
    emoji: "🍞",
    slots: "breakfast",
    servings: 3,
    minutes: 20,
    tags: "vegetarian,kid-friendly,comfort",
    description: "Thick bread soaked long, cooked slow, dusted with icing sugar.",
    ingredients: [
      ["brioche", 6, "slice", "Bakery"],
      ["eggs", 3, "", "Dairy & Eggs"],
      ["milk", 120, "ml", "Dairy & Eggs"],
      ["vanilla extract", 1, "tsp", "Pantry"],
      ["cinnamon", 1, "tsp", "Spices & Herbs"],
      ["strawberries", 200, "g", "Produce"],
      ["blueberries", 100, "g", "Produce"],
      ["butter", 20, "g", "Dairy & Eggs"],
      ["icing sugar", 1, "tbsp", "Pantry"],
    ],
  },
  {
    name: "Smoked Salmon Bagel",
    emoji: "🥯",
    slots: "breakfast,lunch",
    servings: 2,
    minutes: 5,
    tags: "no-cook,high-protein,quick",
    description: "Cream cheese thick enough to be structural, capers piled on top.",
    ingredients: [
      ["bagel", 2, "", "Bakery"],
      ["smoked salmon", 150, "g", "Meat & Seafood"],
      ["cream cheese", 100, "g", "Dairy & Eggs"],
      ["red onion", 0.5, "", "Produce"],
      ["capers", 2, "tbsp", "Pantry"],
      ["lemon", 1, "", "Produce"],
      ["dill", 1, "bunch", "Produce"],
    ],
  },
  {
    name: "Veggie Breakfast Burrito",
    emoji: "🌯",
    slots: "breakfast",
    servings: 2,
    minutes: 20,
    tags: "vegetarian,high-protein",
    description: "Scrambled eggs and roasted peppers wrapped tight and pressed until the outside crisps.",
    ingredients: [
      ["eggs", 4, "", "Dairy & Eggs"],
      ["flour tortilla", 2, "", "Bakery"],
      ["black beans", 200, "g", "Pantry"],
      ["red bell pepper", 1, "", "Produce"],
      ["cheddar", 80, "g", "Dairy & Eggs"],
      ["salsa", 80, "g", "Pantry"],
      ["avocado", 1, "", "Produce"],
      ["cumin", 0.5, "tsp", "Spices & Herbs"],
    ],
  },
  {
    name: "Açaí Smoothie Bowl",
    emoji: "🫐",
    slots: "breakfast",
    servings: 2,
    minutes: 10,
    tags: "vegan,no-cook,high-protein",
    description: "Blended thick enough to eat with a spoon, piled with whatever crunches.",
    ingredients: [
      ["frozen açaí", 200, "g", "Frozen"],
      ["frozen banana", 2, "", "Frozen"],
      ["almond milk", 120, "ml", "Dairy & Eggs"],
      ["granola", 80, "g", "Pantry"],
      ["strawberries", 100, "g", "Produce"],
      ["coconut flakes", 2, "tbsp", "Pantry"],
      ["honey", 1, "tbsp", "Pantry"],
    ],
  },

  // ── Lunch ──────────────────────────────────────────────────────────────────

  {
    name: "Red Lentil Soup",
    emoji: "🍲",
    slots: "lunch,dinner",
    servings: 5,
    minutes: 40,
    tags: "vegan,batch,freezer",
    description: "Cumin-tempered, lemon-finished. Gets better overnight.",
    ingredients: [
      ["red lentils", 300, "g", "Pantry"],
      ["onion", 1, "", "Produce"],
      ["carrot", 2, "", "Produce"],
      ["garlic", 3, "clove", "Produce"],
      ["crushed tomatoes", 400, "g", "Pantry"],
      ["vegetable broth", 1.5, "l", "Pantry"],
      ["cumin", 2, "tsp", "Spices & Herbs"],
      ["smoked paprika", 1, "tsp", "Spices & Herbs"],
      ["lemon", 1, "", "Produce"],
      ["olive oil", 2, "tbsp", "Pantry"],
    ],
  },
  {
    name: "Classic Cobb Salad",
    emoji: "🥗",
    slots: "lunch",
    servings: 2,
    minutes: 15,
    tags: "high-protein,no-cook",
    description: "Everything in rows, blue cheese dressing on the side, no compromises.",
    ingredients: [
      ["chicken breast", 300, "g", "Meat & Seafood"],
      ["bacon", 100, "g", "Meat & Seafood"],
      ["eggs", 2, "", "Dairy & Eggs"],
      ["romaine lettuce", 1, "head", "Produce"],
      ["avocado", 1, "", "Produce"],
      ["cherry tomatoes", 150, "g", "Produce"],
      ["blue cheese", 60, "g", "Dairy & Eggs"],
      ["red wine vinegar", 2, "tbsp", "Pantry"],
      ["olive oil", 3, "tbsp", "Pantry"],
    ],
  },
  {
    name: "Vietnamese Fresh Spring Rolls",
    emoji: "🌿",
    slots: "lunch",
    servings: 3,
    minutes: 25,
    tags: "vegetarian,no-cook,packable",
    description: "Rice paper, cold noodles, herbs piled high. The peanut dipping sauce is the whole point.",
    ingredients: [
      ["rice paper wrappers", 12, "", "Pantry"],
      ["rice vermicelli", 100, "g", "Pantry"],
      ["cucumber", 1, "", "Produce"],
      ["carrot", 2, "", "Produce"],
      ["avocado", 1, "", "Produce"],
      ["mint", 1, "bunch", "Produce"],
      ["peanut butter", 60, "g", "Pantry"],
      ["hoisin sauce", 2, "tbsp", "Pantry"],
      ["lime", 1, "", "Produce"],
    ],
  },
  {
    name: "Nicoise Salad",
    emoji: "🫒",
    slots: "lunch",
    servings: 2,
    minutes: 20,
    tags: "high-protein,packable",
    description: "A proper one: tuna, hard eggs, haricots, olives, all on good greens.",
    ingredients: [
      ["canned tuna", 240, "g", "Pantry"],
      ["eggs", 2, "", "Dairy & Eggs"],
      ["green beans", 200, "g", "Produce"],
      ["baby potatoes", 300, "g", "Produce"],
      ["cherry tomatoes", 150, "g", "Produce"],
      ["kalamata olives", 60, "g", "Pantry"],
      ["mixed greens", 80, "g", "Produce"],
      ["dijon mustard", 1, "tsp", "Pantry"],
      ["olive oil", 3, "tbsp", "Pantry"],
      ["red wine vinegar", 2, "tbsp", "Pantry"],
    ],
  },
  {
    name: "BLT Club Sandwich",
    emoji: "🥪",
    slots: "lunch",
    servings: 2,
    minutes: 15,
    tags: "quick,kid-friendly",
    description: "Three slices, toasted. Bacon cooked until it snaps.",
    ingredients: [
      ["sourdough bread", 6, "slice", "Bakery"],
      ["bacon", 150, "g", "Meat & Seafood"],
      ["romaine lettuce", 0.5, "head", "Produce"],
      ["tomato", 2, "", "Produce"],
      ["mayonnaise", 3, "tbsp", "Pantry"],
      ["avocado", 1, "", "Produce"],
    ],
  },

  // ── Dinner ─────────────────────────────────────────────────────────────────

  {
    name: "Chicken Stir-Fry",
    emoji: "🥢",
    slots: "dinner",
    servings: 3,
    minutes: 25,
    tags: "quick,one-pan,high-protein",
    description: "High heat, quick toss, sauce in at the end so it clings instead of pools.",
    ingredients: [
      ["chicken breast", 500, "g", "Meat & Seafood"],
      ["broccoli", 300, "g", "Produce"],
      ["red bell pepper", 1, "", "Produce"],
      ["snap peas", 150, "g", "Produce"],
      ["soy sauce", 60, "ml", "Pantry"],
      ["oyster sauce", 2, "tbsp", "Pantry"],
      ["garlic", 3, "clove", "Produce"],
      ["ginger", 1, "tbsp", "Produce"],
      ["sesame oil", 1, "tbsp", "Pantry"],
      ["jasmine rice", 250, "g", "Pantry"],
    ],
  },
  {
    name: "Fish Tacos with Slaw",
    emoji: "🌮",
    slots: "dinner",
    servings: 4,
    minutes: 30,
    tags: "quick,high-protein",
    description: "Crispy battered cod, sharp slaw, lime crema. Everything at room temperature except the fish.",
    ingredients: [
      ["cod fillet", 600, "g", "Meat & Seafood"],
      ["corn tortilla", 12, "", "Bakery"],
      ["red cabbage", 200, "g", "Produce"],
      ["carrot", 1, "", "Produce"],
      ["greek yogurt", 150, "g", "Dairy & Eggs"],
      ["lime", 2, "", "Produce"],
      ["flour", 80, "g", "Pantry"],
      ["cumin", 1, "tsp", "Spices & Herbs"],
      ["cilantro", 1, "bunch", "Produce"],
      ["jalapeño", 1, "", "Produce"],
    ],
  },
  {
    name: "Teriyaki Chicken Rice Bowls",
    emoji: "🍱",
    slots: "dinner",
    servings: 4,
    minutes: 30,
    tags: "quick,high-protein,batch",
    description: "Glaze reduced until glossy. Bowls built fast from things you made in bulk.",
    ingredients: [
      ["chicken thighs", 700, "g", "Meat & Seafood"],
      ["soy sauce", 80, "ml", "Pantry"],
      ["mirin", 60, "ml", "Pantry"],
      ["brown sugar", 2, "tbsp", "Pantry"],
      ["jasmine rice", 300, "g", "Pantry"],
      ["broccoli", 250, "g", "Produce"],
      ["scallions", 3, "", "Produce"],
      ["sesame seeds", 1, "tbsp", "Pantry"],
    ],
  },
  {
    name: "Lamb Kofta with Tzatziki",
    emoji: "🫙",
    slots: "dinner",
    servings: 4,
    minutes: 35,
    tags: "high-protein,grill",
    description: "Spiced lamb shaped on skewers, charred fast, served with cold tzatziki and flatbread.",
    ingredients: [
      ["ground lamb", 600, "g", "Meat & Seafood"],
      ["onion", 1, "", "Produce"],
      ["garlic", 3, "clove", "Produce"],
      ["cumin", 1, "tsp", "Spices & Herbs"],
      ["coriander", 1, "tsp", "Spices & Herbs"],
      ["cinnamon", 0.5, "tsp", "Spices & Herbs"],
      ["greek yogurt", 250, "g", "Dairy & Eggs"],
      ["cucumber", 1, "", "Produce"],
      ["mint", 1, "bunch", "Produce"],
      ["pita bread", 4, "", "Bakery"],
      ["lemon", 1, "", "Produce"],
    ],
  },
  {
    name: "White Bean & Kale Soup",
    emoji: "🫘",
    slots: "dinner,lunch",
    servings: 4,
    minutes: 40,
    tags: "vegan,batch,one-pot",
    description: "Cannellini beans, torn kale, and a parmesan rind if you have one.",
    ingredients: [
      ["cannellini beans", 800, "g", "Pantry"],
      ["kale", 200, "g", "Produce"],
      ["onion", 1, "", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["celery", 2, "stalk", "Produce"],
      ["carrot", 2, "", "Produce"],
      ["vegetable broth", 1.5, "l", "Pantry"],
      ["olive oil", 3, "tbsp", "Pantry"],
      ["rosemary", 1, "tbsp", "Spices & Herbs"],
      ["chili flakes", 0.5, "tsp", "Spices & Herbs"],
      ["lemon", 1, "", "Produce"],
    ],
  },
  {
    name: "Tuscan Sausage Pasta",
    emoji: "🍝",
    slots: "dinner",
    servings: 4,
    minutes: 35,
    tags: "comfort,one-pan",
    description: "Sausage browned and broken up, spinach wilted in at the end, cream keeping it together.",
    ingredients: [
      ["italian sausage", 400, "g", "Meat & Seafood"],
      ["rigatoni", 350, "g", "Pantry"],
      ["spinach", 150, "g", "Produce"],
      ["cherry tomatoes", 300, "g", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["heavy cream", 200, "ml", "Dairy & Eggs"],
      ["parmesan", 80, "g", "Dairy & Eggs"],
      ["chili flakes", 0.5, "tsp", "Spices & Herbs"],
      ["olive oil", 2, "tbsp", "Pantry"],
    ],
  },
  {
    name: "Butternut Squash & Coconut Soup",
    emoji: "🎃",
    slots: "dinner,lunch",
    servings: 4,
    minutes: 45,
    tags: "vegan,batch",
    description: "Roast the squash first for colour, then blend everything with coconut milk.",
    ingredients: [
      ["butternut squash", 900, "g", "Produce"],
      ["onion", 1, "", "Produce"],
      ["garlic", 3, "clove", "Produce"],
      ["coconut milk", 400, "ml", "Pantry"],
      ["vegetable broth", 600, "ml", "Pantry"],
      ["ginger", 2, "tbsp", "Produce"],
      ["olive oil", 2, "tbsp", "Pantry"],
      ["cumin", 1, "tsp", "Spices & Herbs"],
      ["lime", 1, "", "Produce"],
    ],
  },
  {
    name: "Honey Garlic Pork Tenderloin",
    emoji: "🍖",
    slots: "dinner",
    servings: 4,
    minutes: 40,
    tags: "high-protein,sheet-pan",
    description: "Seared on the stovetop, finished in the oven, rested properly before slicing.",
    ingredients: [
      ["pork tenderloin", 700, "g", "Meat & Seafood"],
      ["honey", 3, "tbsp", "Pantry"],
      ["soy sauce", 3, "tbsp", "Pantry"],
      ["garlic", 4, "clove", "Produce"],
      ["dijon mustard", 1, "tbsp", "Pantry"],
      ["baby potatoes", 600, "g", "Produce"],
      ["asparagus", 300, "g", "Produce"],
      ["olive oil", 3, "tbsp", "Pantry"],
      ["thyme", 1, "tbsp", "Spices & Herbs"],
    ],
  },
];
