/**
 * Seed recipe library. Ingredient names are lowercase and deliberately
 * consistent across recipes ("crushed tomatoes", not "tinned tomatoes" in one
 * and "tomato passata" in another) so the shopping list can merge them.
 *
 * Ingredient tuple: [name, quantity, unit, aisle]
 */

export const AISLES = [
  "Produce",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Refrigerated",
  "Bakery",
  "Frozen",
  "Pantry",
  "Spices & Herbs",
  "Beverages",
];

/**
 * Each recipe: { name, emoji, slots (comma-separated breakfast|lunch|dinner),
 * servings, minutes, tags, description, ingredients }
 */
export const RECIPES = [
  {
    name: "Greek Yogurt Berry Bowl",
    emoji: "🫐",
    slots: "breakfast",
    servings: 2,
    minutes: 5,
    tags: "vegetarian,no-cook,high-protein",
    description: "Thick yogurt, warm honey, and enough granola for crunch in every spoonful.",
    ingredients: [
      ["greek yogurt", 400, "g", "Dairy & Eggs"],
      ["blueberries", 150, "g", "Produce"],
      ["honey", 2, "tbsp", "Pantry"],
      ["granola", 80, "g", "Pantry"],
      ["almonds", 30, "g", "Pantry"],
    ],
  },
  {
    name: "Spinach Mushroom Omelette",
    emoji: "🍳",
    slots: "breakfast",
    servings: 2,
    minutes: 15,
    tags: "vegetarian,high-protein,low-carb",
    description: "Mushrooms browned properly first, so the eggs stay custardy.",
    ingredients: [
      ["eggs", 4, "", "Dairy & Eggs"],
      ["spinach", 100, "g", "Produce"],
      ["cremini mushrooms", 150, "g", "Produce"],
      ["butter", 15, "g", "Dairy & Eggs"],
      ["parmesan", 30, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Banana Oat Pancakes",
    emoji: "🥞",
    slots: "breakfast",
    servings: 4,
    minutes: 25,
    tags: "vegetarian,kid-friendly,batch",
    description: "Blender batter, no flour. They freeze well, so make the full stack.",
    ingredients: [
      ["rolled oats", 200, "g", "Pantry"],
      ["banana", 2, "", "Produce"],
      ["eggs", 2, "", "Dairy & Eggs"],
      ["milk", 240, "ml", "Dairy & Eggs"],
      ["baking powder", 1, "tsp", "Pantry"],
      ["maple syrup", 60, "ml", "Pantry"],
    ],
  },
  {
    name: "Avocado Toast with Chili Crisp",
    emoji: "🥑",
    slots: "breakfast,lunch",
    servings: 2,
    minutes: 10,
    tags: "vegan,quick",
    description: "Sourdough toasted hard, avocado smashed rough, chili crisp poured without restraint.",
    ingredients: [
      ["sourdough bread", 4, "slice", "Bakery"],
      ["avocado", 2, "", "Produce"],
      ["lime", 1, "", "Produce"],
      ["chili crisp", 2, "tbsp", "Pantry"],
      ["flaky salt", 1, "tsp", "Spices & Herbs"],
    ],
  },
  {
    name: "Peanut Butter Overnight Oats",
    emoji: "🥜",
    slots: "breakfast",
    servings: 2,
    minutes: 5,
    tags: "vegetarian,make-ahead,no-cook",
    description: "Five minutes tonight buys you a breakfast you don't have to think about.",
    ingredients: [
      ["rolled oats", 120, "g", "Pantry"],
      ["milk", 300, "ml", "Dairy & Eggs"],
      ["chia seeds", 2, "tbsp", "Pantry"],
      ["peanut butter", 3, "tbsp", "Pantry"],
      ["banana", 1, "", "Produce"],
    ],
  },
  {
    name: "Shakshuka",
    emoji: "🍅",
    slots: "breakfast,dinner",
    servings: 3,
    minutes: 30,
    tags: "vegetarian,one-pan",
    description: "Eggs poached in spiced tomato until the whites set and the yolks don't.",
    ingredients: [
      ["eggs", 5, "", "Dairy & Eggs"],
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 1, "", "Produce"],
      ["red bell pepper", 1, "", "Produce"],
      ["garlic", 3, "clove", "Produce"],
      ["cumin", 1, "tsp", "Spices & Herbs"],
      ["feta", 100, "g", "Dairy & Eggs"],
      ["cilantro", 1, "bunch", "Produce"],
    ],
  },
  {
    name: "Chickpea Salad Wraps",
    emoji: "🌯",
    slots: "lunch",
    servings: 2,
    minutes: 15,
    tags: "vegetarian,no-cook,packable",
    description: "Mashed chickpeas standing in for tuna, with enough celery to stay crunchy.",
    ingredients: [
      ["chickpeas", 400, "g", "Pantry"],
      ["mayonnaise", 3, "tbsp", "Pantry"],
      ["celery", 2, "stalk", "Produce"],
      ["red onion", 0.5, "", "Produce"],
      ["lemon", 1, "", "Produce"],
      ["flour tortilla", 2, "", "Bakery"],
      ["lettuce", 60, "g", "Produce"],
    ],
  },
  {
    name: "Sesame Soba Noodle Salad",
    emoji: "🍜",
    slots: "lunch",
    servings: 3,
    minutes: 20,
    tags: "vegan,packable,make-ahead",
    description: "Cold noodles, loud dressing. Better on day two than day one.",
    ingredients: [
      ["soba noodles", 250, "g", "Pantry"],
      ["cucumber", 1, "", "Produce"],
      ["carrot", 2, "", "Produce"],
      ["scallions", 4, "", "Produce"],
      ["soy sauce", 45, "ml", "Pantry"],
      ["sesame oil", 2, "tbsp", "Pantry"],
      ["sesame seeds", 2, "tbsp", "Pantry"],
      ["edamame", 200, "g", "Frozen"],
    ],
  },
  {
    name: "Tomato Soup & Grilled Cheese",
    emoji: "🥣",
    slots: "lunch,dinner",
    servings: 4,
    minutes: 35,
    tags: "vegetarian,comfort,kid-friendly",
    description: "The soup gets cream and basil; the sandwich gets butter on the outside.",
    ingredients: [
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 1, "", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["heavy cream", 120, "ml", "Dairy & Eggs"],
      ["basil", 1, "bunch", "Produce"],
      ["sourdough bread", 8, "slice", "Bakery"],
      ["cheddar", 200, "g", "Dairy & Eggs"],
      ["butter", 40, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Turkey Pesto Panini",
    emoji: "🥪",
    slots: "lunch",
    servings: 2,
    minutes: 15,
    tags: "quick,high-protein",
    description: "Press it under something heavy until the cheese leaks and crisps.",
    ingredients: [
      ["ciabatta roll", 2, "", "Bakery"],
      ["sliced turkey", 200, "g", "Meat & Seafood"],
      ["pesto", 60, "g", "Pantry"],
      ["mozzarella", 120, "g", "Dairy & Eggs"],
      ["roasted red pepper", 100, "g", "Pantry"],
      ["arugula", 40, "g", "Produce"],
    ],
  },
  {
    name: "Quinoa Halloumi Bowl",
    emoji: "🥗",
    slots: "lunch,dinner",
    servings: 2,
    minutes: 25,
    tags: "vegetarian,high-protein",
    description: "Halloumi seared until squeaky, over lemony quinoa and cold tomatoes.",
    ingredients: [
      ["quinoa", 150, "g", "Pantry"],
      ["halloumi", 200, "g", "Dairy & Eggs"],
      ["cherry tomatoes", 200, "g", "Produce"],
      ["cucumber", 1, "", "Produce"],
      ["olive oil", 3, "tbsp", "Pantry"],
      ["lemon", 1, "", "Produce"],
      ["mint", 1, "bunch", "Produce"],
    ],
  },
  {
    name: "Black Bean Quesadillas",
    emoji: "🫓",
    slots: "lunch,dinner",
    servings: 3,
    minutes: 20,
    tags: "vegetarian,kid-friendly,quick",
    description: "Crisp tortilla, molten jack, charred corn. Ready before anyone asks twice.",
    ingredients: [
      ["black beans", 400, "g", "Pantry"],
      ["flour tortilla", 6, "", "Bakery"],
      ["monterey jack", 200, "g", "Dairy & Eggs"],
      ["corn", 150, "g", "Frozen"],
      ["scallions", 3, "", "Produce"],
      ["cumin", 1, "tsp", "Spices & Herbs"],
      ["sour cream", 100, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Caprese Orzo Salad",
    emoji: "🍅",
    slots: "lunch",
    servings: 3,
    minutes: 20,
    tags: "vegetarian,packable",
    description: "Orzo dressed while still warm so it drinks up the balsamic.",
    ingredients: [
      ["orzo", 250, "g", "Pantry"],
      ["cherry tomatoes", 300, "g", "Produce"],
      ["mozzarella", 150, "g", "Dairy & Eggs"],
      ["basil", 1, "bunch", "Produce"],
      ["olive oil", 3, "tbsp", "Pantry"],
      ["balsamic vinegar", 2, "tbsp", "Pantry"],
      ["pine nuts", 30, "g", "Pantry"],
    ],
  },
  {
    name: "Sheet-Pan Lemon Chicken",
    emoji: "🍗",
    slots: "dinner",
    servings: 4,
    minutes: 45,
    tags: "one-pan,high-protein",
    description: "Everything on one tray; the potatoes cook in the chicken fat.",
    ingredients: [
      ["chicken thighs", 800, "g", "Meat & Seafood"],
      ["baby potatoes", 700, "g", "Produce"],
      ["lemon", 2, "", "Produce"],
      ["garlic", 6, "clove", "Produce"],
      ["olive oil", 60, "ml", "Pantry"],
      ["rosemary", 2, "tbsp", "Spices & Herbs"],
      ["green beans", 300, "g", "Produce"],
    ],
  },
  {
    name: "Weeknight Bolognese",
    emoji: "🍝",
    slots: "dinner",
    servings: 4,
    minutes: 50,
    tags: "comfort,batch,kid-friendly",
    description: "Not a four-hour ragù, but the soffritto still gets its full ten minutes.",
    ingredients: [
      ["ground beef", 500, "g", "Meat & Seafood"],
      ["spaghetti", 400, "g", "Pantry"],
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 1, "", "Produce"],
      ["carrot", 2, "", "Produce"],
      ["celery", 2, "stalk", "Produce"],
      ["garlic", 3, "clove", "Produce"],
      ["red wine", 120, "ml", "Beverages"],
      ["parmesan", 60, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Thai Green Curry with Tofu",
    emoji: "🍛",
    slots: "dinner",
    servings: 4,
    minutes: 35,
    tags: "vegan,one-pot",
    description: "Fry the paste in coconut cream until it splits — that's where the flavour is.",
    ingredients: [
      ["firm tofu", 400, "g", "Refrigerated"],
      ["coconut milk", 400, "ml", "Pantry"],
      ["green curry paste", 3, "tbsp", "Pantry"],
      ["jasmine rice", 300, "g", "Pantry"],
      ["thai basil", 1, "bunch", "Produce"],
      ["bamboo shoots", 200, "g", "Pantry"],
      ["lime", 2, "", "Produce"],
      ["fish sauce", 1, "tbsp", "Pantry"],
    ],
  },
  {
    name: "Miso Glazed Salmon",
    emoji: "🐟",
    slots: "dinner",
    servings: 2,
    minutes: 25,
    tags: "high-protein,quick",
    description: "Broiled close to the element so the glaze lacquers instead of steaming.",
    ingredients: [
      ["salmon fillet", 400, "g", "Meat & Seafood"],
      ["white miso", 2, "tbsp", "Refrigerated"],
      ["mirin", 2, "tbsp", "Pantry"],
      ["honey", 1, "tbsp", "Pantry"],
      ["jasmine rice", 150, "g", "Pantry"],
      ["bok choy", 300, "g", "Produce"],
      ["ginger", 1, "tbsp", "Produce"],
    ],
  },
  {
    name: "Smoky Black Bean Chili",
    emoji: "🌶️",
    slots: "dinner",
    servings: 5,
    minutes: 55,
    tags: "vegan,batch,freezer",
    description: "Chipotle and smoked paprika doing the work of an all-day simmer.",
    ingredients: [
      ["black beans", 800, "g", "Pantry"],
      ["kidney beans", 400, "g", "Pantry"],
      ["crushed tomatoes", 800, "g", "Pantry"],
      ["onion", 2, "", "Produce"],
      ["red bell pepper", 2, "", "Produce"],
      ["smoked paprika", 1, "tbsp", "Spices & Herbs"],
      ["chipotle in adobo", 2, "tbsp", "Pantry"],
      ["cumin", 1, "tbsp", "Spices & Herbs"],
      ["sour cream", 150, "g", "Dairy & Eggs"],
    ],
  },
  {
    name: "Mushroom Risotto",
    emoji: "🍚",
    slots: "dinner",
    servings: 4,
    minutes: 45,
    tags: "vegetarian,comfort",
    description: "Twenty minutes of stirring, then butter and parmesan off the heat.",
    ingredients: [
      ["arborio rice", 320, "g", "Pantry"],
      ["cremini mushrooms", 400, "g", "Produce"],
      ["shallot", 2, "", "Produce"],
      ["white wine", 150, "ml", "Beverages"],
      ["vegetable broth", 1.2, "l", "Pantry"],
      ["parmesan", 80, "g", "Dairy & Eggs"],
      ["butter", 50, "g", "Dairy & Eggs"],
      ["thyme", 1, "tbsp", "Spices & Herbs"],
    ],
  },
  {
    name: "Korean Beef Bulgogi Bowls",
    emoji: "🥩",
    slots: "dinner",
    servings: 4,
    minutes: 35,
    tags: "high-protein,grill",
    description: "Grated pear in the marinade tenderises the steak and helps it caramelise.",
    ingredients: [
      ["flank steak", 600, "g", "Meat & Seafood"],
      ["soy sauce", 80, "ml", "Pantry"],
      ["brown sugar", 3, "tbsp", "Pantry"],
      ["pear", 1, "", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["sesame oil", 2, "tbsp", "Pantry"],
      ["jasmine rice", 300, "g", "Pantry"],
      ["kimchi", 200, "g", "Refrigerated"],
      ["scallions", 4, "", "Produce"],
    ],
  },
  {
    name: "Roasted Cauliflower Tacos",
    emoji: "🌮",
    slots: "dinner",
    servings: 4,
    minutes: 40,
    tags: "vegetarian,sheet-pan",
    description: "Cauliflower roasted until the edges go black, with a quick chipotle crema.",
    ingredients: [
      ["cauliflower", 800, "g", "Produce"],
      ["corn tortilla", 12, "", "Bakery"],
      ["chipotle in adobo", 1, "tbsp", "Pantry"],
      ["red cabbage", 200, "g", "Produce"],
      ["lime", 2, "", "Produce"],
      ["greek yogurt", 150, "g", "Dairy & Eggs"],
      ["cilantro", 1, "bunch", "Produce"],
      ["cumin", 2, "tsp", "Spices & Herbs"],
    ],
  },
  {
    name: "Lemon Garlic Shrimp Pasta",
    emoji: "🍤",
    slots: "dinner",
    servings: 3,
    minutes: 30,
    tags: "quick,high-protein",
    description: "Shrimp in and out in three minutes; the sauce is butter, lemon, and pasta water.",
    ingredients: [
      ["shrimp", 500, "g", "Meat & Seafood"],
      ["linguine", 300, "g", "Pantry"],
      ["butter", 60, "g", "Dairy & Eggs"],
      ["garlic", 5, "clove", "Produce"],
      ["lemon", 2, "", "Produce"],
      ["parsley", 1, "bunch", "Produce"],
      ["chili flakes", 1, "tsp", "Spices & Herbs"],
      ["white wine", 120, "ml", "Beverages"],
    ],
  },
  {
    name: "Chicken Tikka Masala",
    emoji: "🍛",
    slots: "dinner",
    servings: 4,
    minutes: 50,
    tags: "comfort,high-protein",
    description: "Yogurt-marinated chicken charred first, then folded into a creamy tomato gravy.",
    ingredients: [
      ["chicken breast", 700, "g", "Meat & Seafood"],
      ["greek yogurt", 200, "g", "Dairy & Eggs"],
      ["garam masala", 2, "tbsp", "Spices & Herbs"],
      ["crushed tomatoes", 400, "g", "Pantry"],
      ["heavy cream", 150, "ml", "Dairy & Eggs"],
      ["onion", 1, "", "Produce"],
      ["ginger", 2, "tbsp", "Produce"],
      ["garlic", 4, "clove", "Produce"],
      ["basmati rice", 300, "g", "Pantry"],
      ["naan", 4, "", "Bakery"],
    ],
  },
  {
    name: "Egg Fried Rice",
    emoji: "🍳",
    slots: "lunch,dinner",
    servings: 3,
    minutes: 20,
    tags: "quick,leftovers,kid-friendly",
    description: "Day-old rice, a very hot pan, and everything prepped before you start.",
    ingredients: [
      ["jasmine rice", 300, "g", "Pantry"],
      ["eggs", 3, "", "Dairy & Eggs"],
      ["peas", 150, "g", "Frozen"],
      ["carrot", 1, "", "Produce"],
      ["scallions", 3, "", "Produce"],
      ["soy sauce", 3, "tbsp", "Pantry"],
      ["sesame oil", 1, "tbsp", "Pantry"],
      ["garlic", 2, "clove", "Produce"],
    ],
  },
];
